//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleApp.XsltExtensionObjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExtensionObjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtensionObjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestConsoleApp.XsltExtensionObjects.ExtensionObjectResources", typeof(ExtensionObjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;data&gt;
        ///    &lt;name&gt;some data&lt;/name&gt;
        ///    &lt;Fields&gt;
        ///        &lt;Value&gt;1&lt;/Value&gt;
        ///        &lt;Value&gt;2&lt;/Value&gt;
        ///        &lt;Value&gt;3&lt;/Value&gt;
        ///        &lt;Value&gt;4&lt;/Value&gt;
        ///        &lt;Value&gt;5&lt;/Value&gt;
        ///    &lt;/Fields&gt;
        ///&lt;/data&gt;
        ///.
        /// </summary>
        internal static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;top&gt;
        ///    &lt;first&gt;
        ///        &lt;name&gt;Bob&lt;/name&gt;
        ///    &lt;/first&gt;
        ///    &lt;second&gt;
        ///        &lt;age&gt;30&lt;/age&gt;
        ///    &lt;/second&gt;
        ///&lt;/top&gt;.
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot;
        ///    xmlns:extension=&quot;urn:ExtensionObject&quot;
        ///    exclude-result-prefixes=&quot;msxsl extension&quot;&gt;
        ///    &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///    &lt;xsl:variable name=&quot;ProductId&quot; select=&quot;extension:GetProductId()&quot;/&gt;
        ///    &lt;xsl:variable name=&quot;FundsXPathString&quot;&gt;
        ///        &lt;xsl:text&gt;ComparisonRequest/ProductsRequested/Product[Id=&apos;&lt;/xsl:text&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string transform {
            get {
                return ResourceManager.GetString("transform", resourceCulture);
            }
        }
    }
}
